.eslintrc
.travis.yml
package.json
src/api.js
src/client.js
src/commands.js
src/events.js
src/index.js
src/logger.js
src/parser.js
src/timer.js
src/utils.js

Add ESLint.
_Put an `x` in the boxes that apply_

Chore: add ESLint

---

examples/runkit.js
package.json

Add a RunKit example that will be available from [NPM](https://runkit.com/npm/twitch-js).

Chore: add RunKit example

---

README.md

Reference the Wiki in README.md

Chore: reference Wiki in README.md

---

package.json

Chore: fix RunKit example

---

package.json

Resolves #21.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Bugfix: include examples in published package

---

.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
README.md
examples/runkit.js
package.json

Update organization to [twitch-apis](https://github.com/twitch-apis).

Chore: update organization

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
examples/runkit.js
package.json

Chore: prepare for v2

---

.travis.yml
internals/ci/increment-version.sh
package.json
yarn.lock

Automatically publish to NPM via TravisCI. Version will be automatically incremented; existing pre-release tags will be maintained, while release versions will be given _pre_ pre-release tag. For example:
* `1.2.15` will be published as `1.2.16-pre.0`
* `2.0.0-alpha.2` will be published as `2.0.0-alpha.3`
Release versions (without pre-release tags) will still be manually deployed.

Chore: continuous delivery

---

src/client.js
test/events.js

Parse msg_rejected_mandatory NOTICE message sent from Twitch IRC Server.
PR from [original tmi.js repository](https://github.com/tmijs/tmi.js).

Feature: message moderated event support

---

docs/Chat/Commands.md
docs/Chat/Configuration.md
docs/Examples.md
docs/HomeGettingStarted.md
examples/runkit.js

Hey, I noticed that I forgot some links to the documentation that still pointed to the old one, so here's the correction.

Chore: remove forgotten link to documentation

---

.babelrc
.gitignore
package.json
yarn.lock

Bugfix: babel runtime missing

---

src/__tests__/__fixtures__/events.js
src/__tests__/__fixtures__/events.json
src/__tests__/__snapshots__/client.tests.js.snap
src/__tests__/client.tests.js

Add a test for gifted subscriptions.

Chore: add sub gift test

---

src/api.js

Pass token to api() so that it can be used when an identity is provided.

Bugfix: api() missing token

---

src/api.js

Bugfix: invalid auth header

---

docs/Chat/Events.md
src/client.js
test/events.js

Add event for Twitch raids as well as relevant documentation.

Feature: add support for raid event

---

docs/Chat/Events.md
src/client.js
test/events.js

Feature: add ritual event

---

docs/Chat/Commands.md

Change link in `docs/Chat/Commands.md` to correctly link to `Events.md#Notice`
I'm not entirely sure why the commit has all those extraneous changes, it doesn't seem to affect anything however. *shrug*

Bugfix: fix link location in docs/Chat/Commands.md

---

src/client.js
test/events.js

Handle raid_notice_restricted_chat NOTICE message

Feature: add restricted chat raid NOTICE

---

src/api.js

Fix how options are merged with defaults in "stable" v1 branch. Mainly:
- Account for `_.merge` not doing a deep merge anymore after it's been "improved" in #5
- Do not override method with "GET"

Bugfix: Fix preprocessing of api method's options when using XHR request

---

.github/lock.yml
README.md
package.json
src/utils.js

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

Chore: Add Gitter badge and Lock Threads config

---

__mocks__/ws/__fixtures__/membership.json
__mocks__/ws/index.js
package.json
src/Chat/__tests__/Client.test.js
src/Chat/__tests__/__snapshots__/index.test.js.snap
src/Chat/__tests__/index.test.js

Feature: improve ws mock

---

__e2e__/node/jest.config.js
__e2e__/node/test.e2e.js
src/Api/__tests__/index.test.js
src/Api/constants.js
src/Api/index.js
src/Chat/__tests__/__snapshots__/index.test.js.snap
src/Chat/__tests__/index.test.js
src/Chat/constants.js
src/Chat/index.js
src/__tests__/index.test.js
src/index.js

Feature: allow options to be updated

---

docs/reference/class.md
src/Chat/__tests__/index.test.js
src/Chat/constants.js
src/Chat/index.js

Bugfix: whispers

---

docs/reference/typedef.md
src/Api/__tests__/index.test.js
src/Api/constants.js
src/Api/index.js
src/Api/utils/validators.js

Proposal for #92 and open for alternatives.

Feature: Helix API support

---

src/Chat/__tests__/Client.test.js
src/Chat/__tests__/__snapshots__/index.test.js.snap
src/Chat/__tests__/index.test.js

Alters tests to use Jest property matchers for the ``timestamp`` property.
Hello! Glad to see that tmi.js is thriving somewhere and to see it is getting a ground-up rewrite. I'm super excited. I've made a few minor contributions to tmi.js and was bummed when maintenance dropped off.
Anyways, I forked the next branch and was looking through the codebase. I have never worked on a project that used Jest or tests in any capacity. I've always wanted to learn about testing and this is a great reason to start. I'm always eager to learn new things! …

Chore: Jest property matchers for timestamps

---

index.d.ts

Change reference from path to types to be more generic in declaration.
Dev dependencies are not installed in project.
```
node_modules/twitch-js/index.d.ts(9,22): error TS6053: File '<project>/node_modules/twitch-js/node_modules/@types/ws/index.d.ts' not found.
node_modules/twitch-js/index.d.ts(10,22): error TS6053: File '<project>/node_modules/twitch-js/node_modules/@types/request/index.d.ts' not found.
```
Developer need to install `@types/request` and `@types/ws` on his project
```
yarn add -D @types/request @types/ws
or
npm i -D @types/request @types/ws
```

Bugfix: Fix ws and request declaration not found

---

docs/HomeGettingStarted.md
package.json

Put `@types/request` and `@types/ws` in dependencies to being installed with package.

Bugfix: add @types to project dependencies

---

package.json

Release: v1.2.17
